# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
theme: minimal
day_night: true

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font: "minimal"  # can be: minimal, classic, rose, mr robot, native
font_size: S   # Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)

# Basic Info

# Website type
#   Improve how search engines understand your site.
#   For personal sites, choose "Person".
#   For organizations and projects, choose from https://schema.org/Organization#subtypes
#   E.g. Person, Organization, LocalBusiness, Project, EducationalOrganization
site_type: Organization
local_business_type: ''

# Enter an organization or project name. Defaults to the site title from `config.toml`.
org_name: "Siyang Liu Lab"
# Description for social sharing and search engines. If undefined, superuser role is used in place.
description:

# Display a logo in navigation bar rather than title (optional).
#   To enable, place an image in `assets/media` and reference its filename below. To disable, set the value to "".
logo: ""

# Contact (edit or remove options as required)
email: liusy99@mail.sysu.edu.cn
# phone: 888 888 88 88
address:
  street: Gongchang Road 66, Sun Yat-sen University (Shenzhen Campus)
  region: Guangming District
  city: Shenzhen
  postcode: 518107
  country: China
  country_code: CN
coordinates:
  latitude: 22.8000
  longitude: 113.9446
directions: West Building 1 Medical Garden 4th floor
office_hours:
- 'Monday 10:00 to 13:00'
- 'Wednesday 09:00 to 10:00'
# appointment_url: 'https://calendly.com'
contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://discourse.gohugo.io'

# Address formats: "/data/address_formats.toml"
address_format: en-cn  # en-us

# Site header
main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization
date_format: 'Jan 2, 2006'
time_format: '15:04'

# Site features
highlight: false
math: true
diagram: false
privacy_pack: false

show_related:
  post: true
  project: true
  publication: true
  talk: true

# Show estimated reading time for posts? (true/false) 
reading_time: true

# Display next/previous section pager? (true/false)
section_pager: false

# Enable in-built social sharing buttons? (true/false)
sharing: true

# Link authors to their profile page? (true/false)
link_authors: true


# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`. 未尝试，不确定对不对
plugins_js: []
plugins_css: []

# Get user avatars from Gravatar.com? (true/false)
avatar:
  gravatar: false
  shape: circle

# Configuration of publication pages.
publications:
  # Date format (refer to https://sourcethemes.com/academic/docs/customization/#date-format )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format: "Jan 2, 2006"

  # Citation style ("apa" or "mla")
  citation_style: apa

# Configuration of project pages.
projects:
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view: 2
  publication_view: 2
  talk_view: 2

comments:
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true

  # Comment provider:
  #   1: disqus (https://disqus.com)
  #   2: commento (https://commento.io)
  provider:  # "disqus"  # 可以设为空
  disqus:
    shortname: ''     # Paste the shortname from your Disqus dashboard.
    show_count: true  # Show comment count in page header? (true/false)
  commento:
    url: ''

search:
  provider: wowchemy
  # Configuration of Algolia search engine.
  # Paste the values from your Algolia dashboard.
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false

map:
  # To show your address on a map in the Contact widget, enter your latitude and longitude (above)
  # and choose a map provider below.
  #
  # To use Google Maps, set `engine` to 1 and enter your API key that can be obtained here:
  #   https://developers.google.com/maps/documentation/javascript/get-api-key
  # To use OpenStreetMap tiles, set `engine` to 2.
  # To use OpenStreetMap on a high traffic site, set `engine` to 3 and enter your API key that can be obtained here:
  #   https://www.mapbox.com/studio/account/tokens
  #
  # Map provider:
  #   0: No map
  #   1: Google Maps
  #   2: OpenStreetMap (mapnik)
  #   3: OpenStreetMap (mapbox)
  provider: mapnik
  api_key: ''
  zoom: 15

marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_tongji: ''
  baidu_site_verification: ''

cms:
  branch: main
  local_backend: false

icon:
  pack:
    ai: true

# copyright_license:
#   enable: false
#   allow_derivatives: false
#   share_alike: true
#   allow_commercial: false
#   notice: 'This work is licensed under {license}'




